version: '3'
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - "mysql:/var/lib/mysql"
  
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data  
      
  mongodb:
    image: mongo
    restart: always 
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db  
volumes:
  mysql:  
    external: true
  postgres:
    external: true  
  mongo:
    external: true  